{"level":"fatal","time":"2025-04-18T01:34:50.350Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:34:52.901Z","msg":"Initializing GoogleGenerativeAI..."}
{"level":"info","time":"2025-04-18T01:34:52.901Z","msg":"GoogleGenerativeAI initialized successfully."}
{"level":"info","time":"2025-04-18T01:34:52.901Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","msg":"Attempting to load cache name map"}
{"level":"info","time":"2025-04-18T01:34:54.769Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:34:54.769Z","err":{"type":"Object","message":"Cannot find module './helpers'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\client\\route\\service.ts\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './helpers'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\client\\route\\service.ts\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\client\\route\\service.ts:3:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-33957210827192497.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"info","time":"2025-04-18T01:34:54.823Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","loadedCount":1,"msg":"Successfully loaded cache name entries from file"}
{"level":"fatal","time":"2025-04-18T01:34:54.625Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:34:54.795Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:34:54.796Z","err":{"type":"Object","message":"Cannot find module './helpers'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\client\\route\\service.ts\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './helpers'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\client\\route\\service.ts\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\client\\route\\service.ts:3:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-33957210827192497.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"fatal","time":"2025-04-18T01:35:43.634Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:35:46.743Z","msg":"Initializing GoogleGenerativeAI..."}
{"level":"info","time":"2025-04-18T01:35:46.743Z","msg":"GoogleGenerativeAI initialized successfully."}
{"level":"info","time":"2025-04-18T01:35:46.743Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","msg":"Attempting to load cache name map"}
{"level":"info","time":"2025-04-18T01:35:48.371Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:35:48.371Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-00734094568039434.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"info","time":"2025-04-18T01:35:48.428Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","loadedCount":1,"msg":"Successfully loaded cache name entries from file"}
{"level":"fatal","time":"2025-04-18T01:35:48.238Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:35:48.391Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:35:48.391Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-00734094568039434.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"fatal","time":"2025-04-18T01:35:53.506Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:35:56.877Z","msg":"Initializing GoogleGenerativeAI..."}
{"level":"info","time":"2025-04-18T01:35:56.877Z","msg":"GoogleGenerativeAI initialized successfully."}
{"level":"info","time":"2025-04-18T01:35:56.877Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","msg":"Attempting to load cache name map"}
{"level":"info","time":"2025-04-18T01:35:58.171Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:35:58.171Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-48105043222898347.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"info","time":"2025-04-18T01:35:58.221Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","loadedCount":1,"msg":"Successfully loaded cache name entries from file"}
{"level":"fatal","time":"2025-04-18T01:35:58.060Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:35:58.188Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:35:58.188Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-48105043222898347.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"fatal","time":"2025-04-18T01:36:06.807Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:36:10.198Z","msg":"Initializing GoogleGenerativeAI..."}
{"level":"info","time":"2025-04-18T01:36:10.198Z","msg":"GoogleGenerativeAI initialized successfully."}
{"level":"info","time":"2025-04-18T01:36:10.199Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","msg":"Attempting to load cache name map"}
{"level":"info","time":"2025-04-18T01:36:12.004Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:36:12.004Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-9424931403164163.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"info","time":"2025-04-18T01:36:12.161Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","loadedCount":1,"msg":"Successfully loaded cache name entries from file"}
{"level":"fatal","time":"2025-04-18T01:36:11.803Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:36:12.082Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:36:12.082Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-9424931403164163.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"fatal","time":"2025-04-18T01:36:17.831Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:36:20.714Z","msg":"Initializing GoogleGenerativeAI..."}
{"level":"info","time":"2025-04-18T01:36:20.714Z","msg":"GoogleGenerativeAI initialized successfully."}
{"level":"info","time":"2025-04-18T01:36:20.714Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","msg":"Attempting to load cache name map"}
{"level":"info","time":"2025-04-18T01:36:22.221Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:36:22.221Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-37313455885862234.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"info","time":"2025-04-18T01:36:22.269Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","loadedCount":1,"msg":"Successfully loaded cache name entries from file"}
{"level":"fatal","time":"2025-04-18T01:36:22.104Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:36:22.238Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:36:22.239Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-37313455885862234.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"fatal","time":"2025-04-18T01:36:56.601Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:36:59.696Z","msg":"Initializing GoogleGenerativeAI..."}
{"level":"info","time":"2025-04-18T01:36:59.696Z","msg":"GoogleGenerativeAI initialized successfully."}
{"level":"info","time":"2025-04-18T01:36:59.696Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","msg":"Attempting to load cache name map"}
{"level":"info","time":"2025-04-18T01:37:01.388Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:37:01.388Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-4693776484851031.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"info","time":"2025-04-18T01:37:01.462Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","loadedCount":1,"msg":"Successfully loaded cache name entries from file"}
{"level":"fatal","time":"2025-04-18T01:37:01.249Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:37:01.411Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:37:01.412Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-4693776484851031.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"fatal","time":"2025-04-18T01:37:54.259Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:37:57.987Z","msg":"Initializing GoogleGenerativeAI..."}
{"level":"info","time":"2025-04-18T01:37:57.988Z","msg":"GoogleGenerativeAI initialized successfully."}
{"level":"info","time":"2025-04-18T01:37:57.988Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","msg":"Attempting to load cache name map"}
{"level":"info","time":"2025-04-18T01:38:00.144Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:38:00.145Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-07427503022430137.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"info","time":"2025-04-18T01:38:00.194Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","loadedCount":1,"msg":"Successfully loaded cache name entries from file"}
{"level":"fatal","time":"2025-04-18T01:37:59.992Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:38:00.164Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:38:00.164Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-07427503022430137.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"fatal","time":"2025-04-18T01:42:26.609Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:42:30.532Z","msg":"Initializing GoogleGenerativeAI..."}
{"level":"info","time":"2025-04-18T01:42:30.533Z","msg":"GoogleGenerativeAI initialized successfully."}
{"level":"info","time":"2025-04-18T01:42:30.533Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","msg":"Attempting to load cache name map"}
{"level":"info","time":"2025-04-18T01:42:32.050Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:42:32.050Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-7135769231593274.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"info","time":"2025-04-18T01:42:32.115Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","loadedCount":1,"msg":"Successfully loaded cache name entries from file"}
{"level":"fatal","time":"2025-04-18T01:42:31.922Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:42:32.072Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:42:32.072Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-7135769231593274.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"fatal","time":"2025-04-18T01:42:43.137Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:42:46.678Z","msg":"Initializing GoogleGenerativeAI..."}
{"level":"info","time":"2025-04-18T01:42:46.678Z","msg":"GoogleGenerativeAI initialized successfully."}
{"level":"info","time":"2025-04-18T01:42:46.678Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","msg":"Attempting to load cache name map"}
{"level":"info","time":"2025-04-18T01:42:48.255Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:42:48.256Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-40011930777592797.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"info","time":"2025-04-18T01:42:48.307Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","loadedCount":1,"msg":"Successfully loaded cache name entries from file"}
{"level":"fatal","time":"2025-04-18T01:42:48.145Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:42:48.278Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:42:48.278Z","err":{"type":"Object","message":"Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts","stack":"Error: Cannot find module './client/route/service'\nRequire stack:\n- D:\\NEW-SERVER-TS\\src\\server.ts\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1225:15)\n    at Function._load (node:internal/modules/cjs/loader:1055:27)\n    at TracingChannel.traceSync (node:diagnostics_channel:322:14)\n    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)\n    at Module.require (node:internal/modules/cjs/loader:1311:12)\n    at require (node:internal/modules/helpers:136:16)\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:261:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-40011930777592797.js:69:33)","name":"Error"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"fatal","time":"2025-04-18T01:48:19.739Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:48:22.917Z","msg":"Initializing GoogleGenerativeAI..."}
{"level":"info","time":"2025-04-18T01:48:22.917Z","msg":"GoogleGenerativeAI initialized successfully."}
{"level":"info","time":"2025-04-18T01:48:22.918Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","msg":"Attempting to load cache name map"}
{"level":"info","time":"2025-04-18T01:48:24.316Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:48:24.316Z","err":{"type":"Object","message":"Cannot access 'logger_1' before initialization","stack":"ReferenceError: Cannot access 'logger_1' before initialization\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:18:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-08297597216410946.js:69:33)\n    at node:internal/modules/cjs/loader:1706:10\n    at require.extensions..jsx.require.extensions..js (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-08297597216410946.js:114:20)\n    at require.extensions.<computed> (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-08297597216410946.js:71:20)\n    at Object.nodeDevHook [as .ts] (D:\\NEW-SERVER-TS\\node_modules\\ts-node-dev\\lib\\hook.js:63:13)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)","name":"ReferenceError"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"info","time":"2025-04-18T01:48:24.352Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","loadedCount":1,"msg":"Successfully loaded cache name entries from file"}
{"level":"fatal","time":"2025-04-18T01:48:24.039Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T01:48:24.330Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T01:48:24.330Z","err":{"type":"Object","message":"Cannot access 'logger_1' before initialization","stack":"ReferenceError: Cannot access 'logger_1' before initialization\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:18:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-08297597216410946.js:69:33)\n    at node:internal/modules/cjs/loader:1706:10\n    at require.extensions..jsx.require.extensions..js (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-08297597216410946.js:114:20)\n    at require.extensions.<computed> (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-08297597216410946.js:71:20)\n    at Object.nodeDevHook [as .ts] (D:\\NEW-SERVER-TS\\node_modules\\ts-node-dev\\lib\\hook.js:63:13)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)","name":"ReferenceError"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"fatal","time":"2025-04-18T02:00:02.596Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T02:00:05.391Z","msg":"Initializing GoogleGenerativeAI..."}
{"level":"info","time":"2025-04-18T02:00:05.391Z","msg":"GoogleGenerativeAI initialized successfully."}
{"level":"info","time":"2025-04-18T02:00:05.391Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","msg":"Attempting to load cache name map"}
{"level":"info","time":"2025-04-18T02:00:06.761Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T02:00:06.761Z","err":{"type":"Object","message":"Cannot access 'logger_1' before initialization","stack":"ReferenceError: Cannot access 'logger_1' before initialization\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:18:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-017822181521604863.js:69:33)\n    at node:internal/modules/cjs/loader:1706:10\n    at require.extensions..jsx.require.extensions..js (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-017822181521604863.js:114:20)\n    at require.extensions.<computed> (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-017822181521604863.js:71:20)\n    at Object.nodeDevHook [as .ts] (D:\\NEW-SERVER-TS\\node_modules\\ts-node-dev\\lib\\hook.js:63:13)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)","name":"ReferenceError"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"info","time":"2025-04-18T02:00:06.806Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","loadedCount":1,"msg":"Successfully loaded cache name entries from file"}
{"level":"fatal","time":"2025-04-18T02:00:06.496Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T02:00:06.783Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T02:00:06.784Z","err":{"type":"Object","message":"Cannot access 'logger_1' before initialization","stack":"ReferenceError: Cannot access 'logger_1' before initialization\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:18:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-017822181521604863.js:69:33)\n    at node:internal/modules/cjs/loader:1706:10\n    at require.extensions..jsx.require.extensions..js (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-017822181521604863.js:114:20)\n    at require.extensions.<computed> (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-017822181521604863.js:71:20)\n    at Object.nodeDevHook [as .ts] (D:\\NEW-SERVER-TS\\node_modules\\ts-node-dev\\lib\\hook.js:63:13)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)","name":"ReferenceError"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"fatal","time":"2025-04-18T02:00:53.801Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T02:00:57.300Z","msg":"Initializing GoogleGenerativeAI..."}
{"level":"info","time":"2025-04-18T02:00:57.300Z","msg":"GoogleGenerativeAI initialized successfully."}
{"level":"info","time":"2025-04-18T02:00:57.300Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","msg":"Attempting to load cache name map"}
{"level":"info","time":"2025-04-18T02:00:59.296Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T02:00:59.296Z","err":{"type":"Object","message":"Cannot access 'logger_1' before initialization","stack":"ReferenceError: Cannot access 'logger_1' before initialization\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:18:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-7407540907374264.js:69:33)\n    at node:internal/modules/cjs/loader:1706:10\n    at require.extensions..jsx.require.extensions..js (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-7407540907374264.js:114:20)\n    at require.extensions.<computed> (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-7407540907374264.js:71:20)\n    at Object.nodeDevHook [as .ts] (D:\\NEW-SERVER-TS\\node_modules\\ts-node-dev\\lib\\hook.js:63:13)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)","name":"ReferenceError"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"info","time":"2025-04-18T02:00:59.399Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","loadedCount":1,"msg":"Successfully loaded cache name entries from file"}
{"level":"fatal","time":"2025-04-18T02:00:58.858Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T02:00:59.347Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T02:00:59.347Z","err":{"type":"Object","message":"Cannot access 'logger_1' before initialization","stack":"ReferenceError: Cannot access 'logger_1' before initialization\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:18:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-7407540907374264.js:69:33)\n    at node:internal/modules/cjs/loader:1706:10\n    at require.extensions..jsx.require.extensions..js (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-7407540907374264.js:114:20)\n    at require.extensions.<computed> (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-7407540907374264.js:71:20)\n    at Object.nodeDevHook [as .ts] (D:\\NEW-SERVER-TS\\node_modules\\ts-node-dev\\lib\\hook.js:63:13)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)","name":"ReferenceError"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"fatal","time":"2025-04-18T02:06:57.467Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T02:07:00.243Z","msg":"Initializing GoogleGenerativeAI..."}
{"level":"info","time":"2025-04-18T02:07:00.243Z","msg":"GoogleGenerativeAI initialized successfully."}
{"level":"info","time":"2025-04-18T02:07:00.243Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","msg":"Attempting to load cache name map"}
{"level":"info","time":"2025-04-18T02:07:01.670Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T02:07:01.670Z","err":{"type":"Object","message":"Cannot access 'logger_1' before initialization","stack":"ReferenceError: Cannot access 'logger_1' before initialization\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:18:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-44930445575575395.js:69:33)\n    at node:internal/modules/cjs/loader:1706:10\n    at require.extensions..jsx.require.extensions..js (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-44930445575575395.js:114:20)\n    at require.extensions.<computed> (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-44930445575575395.js:71:20)\n    at Object.nodeDevHook [as .ts] (D:\\NEW-SERVER-TS\\node_modules\\ts-node-dev\\lib\\hook.js:63:13)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)","name":"ReferenceError"},"msg":"Error triggered shutdown (uncaughtException)"}
{"level":"info","time":"2025-04-18T02:07:01.727Z","filePath":"D:\\NEW-SERVER-TS\\src\\conference\\data\\gemini_cache_map.json","function":"loadCacheNameMap","loadedCount":1,"msg":"Successfully loaded cache name entries from file"}
{"level":"fatal","time":"2025-04-18T02:07:01.400Z","initCheck":true,"msg":"LOGGER INITIALIZED (pino.destination). This should appear in the log file."}
{"level":"info","time":"2025-04-18T02:07:01.686Z","msg":"Received uncaughtException. Shutting down gracefully..."}
{"level":"error","time":"2025-04-18T02:07:01.686Z","err":{"type":"Object","message":"Cannot access 'logger_1' before initialization","stack":"ReferenceError: Cannot access 'logger_1' before initialization\n    at Object.<anonymous> (D:\\NEW-SERVER-TS\\src\\server.ts:18:1)\n    at Module.<anonymous> (node:internal/modules/cjs/loader:1554:14)\n    at Module._compile (D:\\NEW-SERVER-TS\\node_modules\\source-map-support\\source-map-support.js:568:25)\n    at Module.m._compile (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-44930445575575395.js:69:33)\n    at node:internal/modules/cjs/loader:1706:10\n    at require.extensions..jsx.require.extensions..js (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-44930445575575395.js:114:20)\n    at require.extensions.<computed> (C:\\Users\\LELOI~1\\AppData\\Local\\Temp\\ts-node-dev-hook-44930445575575395.js:71:20)\n    at Object.nodeDevHook [as .ts] (D:\\NEW-SERVER-TS\\node_modules\\ts-node-dev\\lib\\hook.js:63:13)\n    at Module.load (node:internal/modules/cjs/loader:1289:32)\n    at Function._load (node:internal/modules/cjs/loader:1108:12)","name":"ReferenceError"},"msg":"Error triggered shutdown (uncaughtException)"}
